from __future__ import annotations

ROLE_PERMISSIONS: dict[str, tuple[str, ...]] = {
    "admin": (
        "workspace.read",
        "workspace.update",
        "members.read",
        "members.create",
        "members.update",
        "members.deactivate",
        "sessions.manage",
        "members.reset_password",
        "leads.read",
        "leads.create",
        "leads.update",
        "leads.assign",
        "pipeline.read",
        "pipeline.update",
        "activities.read",
        "activities.create",
        "activities.update",
        "analytics.read",
        "audit.read",
        "settings.read",
        "settings.update",
        "atlas.use",
        "atlas.execute",
    ),
    "manager": (
        "workspace.read",
        "members.read",
        "members.create",
        "members.update",
        "leads.read",
        "leads.create",
        "leads.update",
        "leads.assign",
        "pipeline.read",
        "pipeline.update",
        "activities.read",
        "activities.create",
        "activities.update",
        "analytics.read",
        "audit.read",
        "settings.read",
        "atlas.use",
        "atlas.execute",
    ),
    "seller": (
        "workspace.read",
        "members.read",
        "leads.read",
        "leads.create",
        "leads.update",
        "pipeline.read",
        "pipeline.update",
        "activities.read",
        "activities.create",
        "activities.update",
        "atlas.use",
    ),
    "operator": (
        "workspace.read",
        "members.read",
        "leads.read",
        "leads.create",
        "leads.update",
        "pipeline.read",
        "activities.read",
        "activities.create",
        "activities.update",
    ),
}

VALID_ROLES = frozenset(ROLE_PERMISSIONS)


def get_permissions_for_role(role: str) -> tuple[str, ...]:
    return ROLE_PERMISSIONS.get(role.strip().lower(), ())
